version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: teste_compass_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: compass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/teste_compass_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: compass123
    ports:
      - "8080:8080"
    command: ["java", "-jar", "app.jar"]

volumes:
  postgres_data: